services:
  - type: web
    name: caderneta-django
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn caderneta_project.wsgi"
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: caderneta-db
          property: connectionString

databases:
  - name: caderneta-db
    plan: free
