# Generated by Django 5.2.2 on 2025-06-07 01:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gravida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_ultima_menstruacao', models.DateField()),
                ('data_provavel_parto', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(max_length=100)),
                ('resultado', models.TextField()),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('gravida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='caderneta.gravida')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=100)),
                ('profissional', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressao_arterial', models.CharField(max_length=10)),
                ('altura_uterina', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('batimentos_cardiacos_fetais', models.IntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('gravida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='caderneta.gravida')),
            ],
        ),
    ]
