# Generated by Django 5.2.2 on 2025-06-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caderneta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gravida',
            name='cpf',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número do BI'),
        ),
    ]
