# Generated by Django 5.2.2 on 2025-06-14 23:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caderneta', '0002_change_cpf_to_bi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaGravida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('gravida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagina_gravida', to='caderneta.gravida')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagina_gravida', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LembreteGravida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo_lembrete', models.CharField(choices=[('medicamento', 'Medicamento'), ('consulta', 'Consulta'), ('exame', 'Exame'), ('exercicio', 'Exercício'), ('alimentacao', 'Alimentação'), ('vitamina', 'Vitamina/Suplemento'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('data_lembrete', models.DateTimeField()),
                ('repetir', models.BooleanField(default=False)),
                ('intervalo_repeticao', models.IntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('concluido', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('pagina_gravida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='caderneta.paginagravida')),
            ],
            options={
                'ordering': ['data_lembrete'],
            },
        ),
        migrations.CreateModel(
            name='ControleGestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.CharField(choices=[('peso', 'Peso'), ('pressao', 'Pressão Arterial'), ('sintomas', 'Sintomas'), ('medicamentos', 'Medicamentos'), ('alimentacao', 'Alimentação'), ('exercicios', 'Exercícios'), ('humor', 'Humor/Bem-estar'), ('movimento_fetal', 'Movimento Fetal'), ('outros', 'Outros')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidade', models.CharField(blank=True, max_length=20, null=True)),
                ('data_registro', models.DateTimeField()),
                ('importante', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('pagina_gravida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_gestacao', to='caderneta.paginagravida')),
            ],
            options={
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='ConsultaAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_consulta', models.CharField(choices=[('prenatal', 'Pré-natal'), ('ultrassom', 'Ultrassom'), ('exame', 'Exame'), ('emergencia', 'Emergência'), ('rotina', 'Consulta de Rotina')], default='prenatal', max_length=20)),
                ('data_consulta', models.DateTimeField()),
                ('local', models.CharField(max_length=200)),
                ('profissional', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone_contato', models.CharField(blank=True, max_length=15, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('remarcada', 'Remarcada')], default='agendada', max_length=20)),
                ('lembrete_enviado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('pagina_gravida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_agendadas', to='caderneta.paginagravida')),
            ],
            options={
                'ordering': ['data_consulta'],
            },
        ),
    ]
